# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160428_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default=b'onion', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.CharField(blank=True, default=b'blog_default.png', max_length=200),
        ),
    ]
