# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160428_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='reads',
            field=models.IntegerField(default=0),
        ),
    ]
