# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160428_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
